### ISSUE TITLE
Responsive field width

### ISSUE THREAD

**Issue by slemale** [SahilATech/ChoiceRestrictor#2]
Hello Sahil,

Testing your PCF component with different optionsets made be realize it is responsive to values width, not form width.
Then when a selected value has smaller width than other values, then these other values are not fully displayed.
See below : 

![image](https://github.com/user-attachments/assets/faa006a0-8f8f-4235-93aa-dc3457842f74)

The selected value "Other Type" is smaller than the other values and we cannot read all values properly.
Is it possible to adapt the component to make it responsive to the form, like a normal optionset would do ?

![image](https://github.com/user-attachments/assets/53ef1f28-57ad-4e5f-acea-1a9523020eb2)

Thanks for the help.

Sébastien.

**Comment by SahilATech** [comment]
I'm not sure why you're able to face this. I've updated the Solution file again, try to import it again. [Solutions](https://github.com/SahilATech/ChoiceRestrictor/tree/6a9c3b43a6f3db7a10251ea47dde1143f9edfb6e/Solutions)

![image](https://github.com/user-attachments/assets/07d1170f-0865-4451-bcea-42a8fa2a0e5a)

![image](https://github.com/user-attachments/assets/8efaa87c-c4c3-4c28-b73b-04babf022bce)

**Comment by slemale** [comment]
Hello Sahil,

I tried with both solutions managed and unmanaged. I tried on another field, on another form. Still get the same display, where the field is reponsive to the value, not the form.

Thanks for the help.

Sébastien.
